const express = require('express');
const router = express.Router();
const { CrearRemisionController } = require('../../../controllers/comercial/remisiones/CrearRemisionController');
const { VerCantidadDisponibleController } = require('../../../controllers/comercial/remisiones/VerCantidadDisponibleController');
const { ConsultarSiguienteNoRemisionController } = require('../../../controllers/comercial/remisiones/ConsultarSiguienteNoRemisionController');
const { ConsultarRemisionesController } = require('../../../controllers/comercial/remisiones/ConsultarRemisionesController');
const { GenerarPDFRemisionController } = require('../../../controllers/comercial/remisiones/GenerarPDFController')
const { EliminarRemisionController } = require('../../../controllers/comercial/remisiones/EliminarRemisionController');
const { VerDisponibilidadEquiposController } = require('../../../controllers/comercial/remisiones/VerDisponibilidadEquiposController');
const { VerDisponibilidadEquiposGeneralesController } = require('../../../controllers/comercial/remisiones/VerDisponibilidadEquiposGeneralesController');
const { VerCantidadRemisionesYDevolucionesUltimos6MesesController } = require('../../../controllers/comercial/remisiones/VerCantidadRemisionesYDevolucionesUltimos6MesesController');
const { VerTotalesMovimientosMesActualController } = require('../../../controllers/comercial/remisiones/VerTotalesMovimientosMesActualController');
const { VerActividadRecienteMovimientosController } = require('../../../controllers/comercial/remisiones/VerActividadRecienteMovimientosController');
const { VerRemisionPorIdController } = require('../../../controllers/comercial/remisiones/VerRemisionPorIdController');
const { ActualizarRemisionController } = require('../../../controllers/comercial/remisiones/ActualizarRemisionController');

router.post('/crear-remision', CrearRemisionController);
router.put('/actualizar-remision', ActualizarRemisionController);
router.get('/ver-remision-por-id', VerRemisionPorIdController);
router.get('/ver-cantidad-disponible-equipo/:IdEquipo', VerCantidadDisponibleController);
router.get('/siguiente-no-remision', ConsultarSiguienteNoRemisionController);
router.get('/ver-remisiones', ConsultarRemisionesController);
router.get('/obtener-pdf-remision/:IdRemision', GenerarPDFRemisionController);
router.delete('/eliminar-remision', EliminarRemisionController);
router.get('/ver-disponibilidad-equipos', VerDisponibilidadEquiposController);
router.get('/ver-disponibilidad-equipos-generales', VerDisponibilidadEquiposGeneralesController);
router.get('/cantidad-remisiones-devoluciones-ultimos-6-meses', VerCantidadRemisionesYDevolucionesUltimos6MesesController);
router.get('/totales-movimientos-mes-actual', VerTotalesMovimientosMesActualController);
router.get('/actividad-reciente-movimientos', VerActividadRecienteMovimientosController);
module.exports = router;
