/* 
    - LOS INDICES POR LO GENERAL SE CREAN PARA DAR MEJOR RENDIMIENTO A LAS CONSULTAS/QUERYS, SI LA COLUMNA YA ES PRIMARY KEY, NO ES NECESARIO CREAR UN INDICE SOBRE ESA COLUMNA 
    - SE CREAN PARA COLUMNAS INVOLUCRADAS EN ( INNER, LEFT, RIGHT / JOIN ) Y EN CONDICIONES WHERE.
*/

-- PARA VERIFICAR QUE REALMENTE SE ESTÁN MANEJANDO LOS INDICES IMPLEMENTADOS
EXPLAIN ANALYZE
SELECT
  ...tu query completo...
WHERE devo.IdDevolucion = 123;
-- NOTA: DEBE APARECER:
Index Scan using idx_devoluciones_iddevolucion ...
-- EN LUGAR DE:
Seq Scan on devoluciones
